name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  lxc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable
    - name: Install distrobuilder
      run: |
        sudo apt-get update >/dev/null
        sudo snap install distrobuilder --classic
        sudo apt-get -y install lxc debootstrap squashfs-tools awscli >/dev/null
        distrobuilder --version
        lxc image list # local images
        lxc image list images: # public images
    - name: Launch container
      run: |
        sudo distrobuilder build-lxd ubuntu.yaml -o image.architecture=amd64 -o image.release=focal
        lxd init --auto
        lxd init --dump
        lxc image import lxd.tar.xz rootfs.squashfs --alias my-local-image
        lxc image list
        time lxc launch my-local-image mycontainer
    - name: Waiting for network
      run: |
        lxc exec mycontainer -- timeout 2m bash -c 'echo waiting for newtork; until ping -c 1 google.com &>/dev/null; do sleep 1; done'
